version: 2

sources:
  - name: erp
    description: Banco réplica do erp da northwind.
    schema: erp_northwind
    tables:
      - name: orders
        description: Uma linha por pedido. Inclui pedidos cancelados e deletados.
        columns:
          - name: order_id
            description: Chave primária da tabela de ordens.
            tests:
              - unique
              - not_null